alias c='clear'
alias lg='lazygit'
alias port-forwarding='~/scripts/port_forwarding.sh'
alias unitstatus='~/scripts/unitstatus.sh'
alias cu='~/scripts/checkupdates.sh'
alias wt='source ~/scripts/git_worktree.sh'
alias sup='flatpak update && yay'
alias bright='systemctl --user restart plasma-powerdevil.service'
alias ncdu='ncdu --color dark'
alias s='kitten ssh'
alias v='nvim'
alias awt='~/scripts/analyze-worktrees.sh'
alias oc='opencode'
alias testapi='NODE_NO_WARNINGS=1 npmR test:api --'
alias testapi-p='NODE_NO_WARNINGS=1 npmR test:api-p -- -j 11'
alias testfile='~/scripts/testfile.sh'
alias headset-battery='~/scripts/logitech_headset_battery.sh'
alias bup='git pull && npm install'
