$terminal = ghostty
$fileManager = thunar
$browser = brave
$ipc = qs -c noctalia-shell ipc call

$focus_or_launch = ~/scripts/focus_or_launch.sh

bind = SUPER, Q, killactive,
bind = SUPER SHIFT, Delete, exit,
bind = SUPER SHIFT, F, togglefloating,
bind = SUPER, J, layoutmsg, togglesplit
bind = SUPER, R, layoutmsg, movetoroot
bind = SUPER, F, fullscreen,
bind = SUPER SHIFT, P, pin,

bind = SUPER, Space, exec, $ipc launcher toggle
bind = SUPER, C, exec, $ipc controlCenter toggle
bind = SUPER, comma, exec, $ipc settings toggle
bind = SUPER, L, exec, $ipc lockScreen lock
bind = SUPER, V, exec, $ipc launcher clipboard
bind = SUPER, semicolon, exec, $ipc launcher emoji
bind = SUPER, W, exec, $ipc wallpaper toggle
bind = SUPER SHIFT, W, exec, $ipc wallpaper random all
bind = SUPER, N, exec, $ipc notifications toggleHistory
bind = SUPER SHIFT, N, exec, $ipc notifications toggleDND
bind = SUPER, Delete, exec, $ipc sessionMenu toggle
bind = SUPER, T, exec, $ipc darkMode toggle
bind = SUPER SHIFT, T, exec, $ipc nightLight toggle
bind = , Pause, exec, $ipc media playPause
bindel = , XF86AudioRaiseVolume, exec, $ipc volume increase
bindel = , XF86AudioLowerVolume, exec, $ipc volume decrease
bindl = , XF86AudioMute, exec, $ipc volume muteOutput
bindel = , XF86MonBrightnessUp, exec, $ipc brightness increase
bindel = , XF86MonBrightnessDown, exec, $ipc brightness decrease
bind = SUPER, A, exec, $ipc volume togglePanel
bind = SHIFT, XF86AudioRaiseVolume, exec, $ipc brightness increase
bind = SHIFT, XF86AudioLowerVolume, exec, $ipc brightness decrease

# bind = SUPER, TAB, hyprview:toggle,

bind = SUPER, Return, exec, $terminal
bind = SUPER, E, exec, $fileManager
bind = SUPER, B, exec, $browser
# bind = SUPER, A, exec, pkill pavucontrol-qt || pavucontrol-qt --tab 3
bind = SUPER SHIFT, V, exec, $focus_or_launch protonvpn-app protonvpn-app
bind = SUPER, O, exec, $focus_or_launch obsidian obsidian
bind = SUPER, S, exec, $focus_or_launch spotify spotify
bind = SUPER, P, exec, $focus_or_launch "Proton Pass" proton-pass
bind = SUPER, D, exec, wayscriber --active --freeze
bind = SUPER, Escape, exec, ghostty -e btop

bind = , Print, exec, grimblast -f copysave area ~/Images/Screenshots/"$(date)".png
bind = SUPER, Print, exec, grimblast copysave screen ~/Images/Screenshots/"$(date)".png
bind = CTRL, Print, exec, grimblast copysave active ~/Images/Screenshots/"$(date)".png

bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d
bind = SUPER SHIFT, left, movewindow, l
bind = SUPER SHIFT, right, movewindow, r
bind = SUPER SHIFT, up, movewindow, u
bind = SUPER SHIFT, down, movewindow, d

bind = SUPER, ampersand, workspace, 1
bind = SUPER, eacute, workspace, 2
bind = SUPER, quotedbl, workspace, 3
bind = SUPER, apostrophe, workspace, 4
bind = SUPER, parenleft, workspace, 5
bind = SUPER, minus, workspace, 6
bind = SUPER, egrave, workspace, 7
bind = SUPER, underscore, workspace, 8
bind = SUPER, ccedilla, workspace, 9
bind = SUPER, agrave, workspace, 10

bind = SUPER SHIFT, ampersand, movetoworkspace, 1
bind = SUPER SHIFT, eacute, movetoworkspace, 2
bind = SUPER SHIFT, quotedbl, movetoworkspace, 3
bind = SUPER SHIFT, apostrophe, movetoworkspace, 4
bind = SUPER SHIFT, parenleft, movetoworkspace, 5
bind = SUPER SHIFT, minus, movetoworkspace, 6
bind = SUPER SHIFT, egrave, movetoworkspace, 7
bind = SUPER SHIFT, underscore, movetoworkspace, 8
bind = SUPER SHIFT, ccedilla, movetoworkspace, 9
bind = SUPER SHIFT, agrave, movetoworkspace, 10

bind = SUPER, mouse_up, workspace, e+1
bind = SUPER, mouse_down, workspace, e-1

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
