# Monitors config
monitor=DP-2,2560x1440@170,0x0,1,vrr,1
monitor=,preferred,auto,1

# Sources
source = ./startup.conf
source = ./windowRules.conf
source = ./binds.conf

# Default env vars
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt5ct # change to qt6ct if you have that

# Keyboard, mouse, etc.
input {
    kb_layout = fr
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1
    touchpad {
        natural_scroll = false
    }
    # -1.0 - 1.0, 0 means no modification.
    sensitivity = 0
    accel_profile = flat
}

general {
    gaps_in = 8
    gaps_out = 16
    border_size = 3
    col.active_border = rgb(FFADF3) rgb(6ADBF5) 45deg
    col.inactive_border = rgba(FFF9FD4C)
    layout = dwindle
    allow_tearing = false
}

decoration {
    rounding = 10
    blur {
        enabled = true
        size = 4
        passes = 2
    }
    drop_shadow = true
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)
    active_opacity = 1
    inactive_opacity = 0.8
    dim_inactive = true
    dim_strength = 0.1
}

animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    pseudotile = yes
    preserve_split = yes
}

master {
    new_is_master = true
}

gestures {
    workspace_swipe = off
}

misc {
    disable_hyprland_logo = true
    force_default_wallpaper = 0
}
