exec-once = swaync
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = hyprpaper
exec-once = hypridle
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Waybar
exec-once = waybar -c ~/dotfiles/.config/waybar/chromatic_config -s ~/dotfiles/.config/waybar/chromatic_style.css
