general {
    gaps_in = 5
    gaps_out = 10

    border_size = 2

    col.active_border = $mauve $pink $lavender
    col.inactive_border = $base

    resize_on_border = false

    allow_tearing = false

    layout = dwindle
}

decoration {
    rounding = 20
    rounding_power = 2

    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = $mantle
    }

    blur {
        enabled = true
        size = 8
        passes = 4
        noise = 0.02
    }
}

animations {
    enabled = yes

    bezier = punch, 0.46, 1.8, 0.29, 0.82
    bezier = snappy, 0.22, 1.2, 0.36, 1.0
    bezier = zipOut, 0.55, 0.0, 1.0, 0.45
    bezier = overshot, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 3, punch, popin 75%
    animation = windowsOut, 1, 2, zipOut, popin 90%
    animation = windowsMove, 1, 3, snappy, slide
    animation = fade, 1, 2, snappy
    animation = fadeOut, 1, 2, zipOut
    animation = workspaces, 1, 3, overshot, slide
    animation = specialWorkspace, 1, 3, snappy, slidevert
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}
