# Firefox PIP
windowrulev2 = float, class:firefox, title:Incrustation vidéo
windowrulev2 = move onscreen 100%-8, class:firefox, title:Incrustation vidéo
windowrulev2 = pin, class:firefox, title:Incrustation vidéo
windowrulev2 = opacity 1 override, class:firefox, title:Incrustation vidéo
# Pavucontrol
windowrulev2 = float, class:pavucontrol
# Steam contacts
windowrulev2 = float, class:steam, title:Liste de contacts
