#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "dracula"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    # autocomplete method
    autocomplete_method = "coc"
    # bootstraps
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 20

# Language server protocol
[[layers]]
name = "lsp"

# Javascript code completion
[[layers]]
name = "lang#javascript"
enable_flow_syntax = true
format_on_save = true
# Toml code completion
[[layers]]
name = "lang#toml"
# Vimscripting code completion
[[layers]]
name = "lang#vim"
# Html code completion
[[layers]]
name = "lang#html"
emmet_leader_key = "<C-e>"
emmet_filetyps = ['html', 'hbs', 'twig']

# Write file with elevated privileges
[[layers]]
name = "sudo"

# Checkers
[[layers]]
name = "checkers"
lint_on_the_fly = true

[[layers]]
name = "colorscheme"

# Git integration
[[layers]]
name = "git"
[[layers]]
name = "VersionControl"

# Show number of occurences when searching 
[[layers]]
name = "incsearch"

# CtrlP
[[layers]]
name = "ctrlp"

# disable core statusline
# [[layers]]
# name = "core#statusline"
# enable = false

# dracula colorscheme
[[custom_plugins]]
repo = "dracula/vim"
name = "dracula"
merged = false

# Airline statusbar
# [[custom_plugins]]
# repo = "vim-airline/vim-airline"
# merged = false
# [[custom_plugins]]
# repo = "vim-airline/vim-airline-themes"
# merged = false
